### ISSUE TITLE
Performance impact

### ISSUE THREAD

**Issue by Tyrannicodin** [deepsidh9/Live-Valorant-Overlay#2]
Great project, I've been looking for something like this for a long time. Just wondering how much this impacts the performance?

**Comment by deepsidh9** [comment]
The way it works is that it takes screenshots every 1 second and processes the image. Performance also depends on what features you've enabled; with OCR enabled, I was getting frame drops from 120/130 to around 80/90 if I was recording too.  Without OCR and recording, I got 120 FPS and faster processing of images. I've not tested how the scenario is if you are just a spectator. If you feel that running this app locally takes a big toll on your resources, I think you can offload the processing to a remote server if you've less network latency, haven't tested that also.
