### ISSUE TITLE
Module

### ISSUE THREAD

**Issue by therealpintoss** [deepsidh9/Live-Valorant-Overlay#4]
I downloaded all the things that you said but i'm taking this error:
![image](https://user-images.githubusercontent.com/69796025/148104685-97748d48-dad8-4136-8798-0a881233227b.png)
Can you help me please?

**Comment by deepsidh9** [comment]
It says that the module "flask" is not found. Did you install all the dependencies by following the instructions given [here](https://github.com/deepsidh9/Live-Valorant-Overlay/tree/1920x1080#installation)?

**Comment by therealpintoss** [comment]
yep, i installed

**Comment by therealpintoss** [comment]
ups! i got it. i installed everything again and the problem is gone. thanks for trying to help me!

**Comment by therealpintoss** [comment]
ummm, i have a new question :) 
![image](https://user-images.githubusercontent.com/69796025/148109379-0670abb7-b77b-43f9-857c-d8cedda84262.png)
Can u hep me?

**Comment by deepsidh9** [comment]
Can you share the full error?

**Comment by therealpintoss** [comment]
![image](https://user-images.githubusercontent.com/69796025/148112258-eb643c4b-03d2-49b3-b6ff-062520111b22.png)
![image](https://user-images.githubusercontent.com/69796025/148112361-41d7b137-6ad9-491a-b4b6-2e709f3c7ee8.png)

**Comment by deepsidh9** [comment]
Have a look [here](https://github.com/JaidedAI/EasyOCR/issues/195). If this doesn't work then try to install torch first and sometimes it doesn't install when you have the 3.10 python version as it isn't available for that version yet.

**Comment by therealpintoss** [comment]
I uninstalled it and installed python 3.9 but i have a new problem in observer mode program is not working

**Comment by deepsidh9** [comment]
[This commit](https://github.com/deepsidh9/Live-Valorant-Overlay/commit/bdc633ae07d373f2025b42d8147930f51721abdb) fixes the observer mode issue.
