### ISSUE TITLE
Not working when only a single player is present

### ISSUE THREAD

**Issue by pintosobs** [deepsidh9/Live-Valorant-Overlay#5]
I'm sory for that thats my 3th problem but i really need help. Everything is ok but while im ingame this program is not seeing that im alive or i have ult etc. 
![image](https://user-images.githubusercontent.com/69796025/148416065-45aceada-ba2a-4bc6-94e2-dd9fb79b461e.png)
![image](https://user-images.githubusercontent.com/69796025/148416102-99748c0c-77e9-477a-a672-32b839cd8c55.png)
As you can see i have this problems, can u help me?

**Comment by deepsidh9** [comment]
This application's information retrieval system works when there are a total of 10 players in the game. So a spike rush, unrated or competitive game would reflect that information, not for anything less than 10 players.

**Comment by pintosobs** [comment]
ok thank you im gonna try and give you feedback

**Comment by pintosobs** [comment]
![image](https://user-images.githubusercontent.com/69796025/148424773-ed76c6c0-edfe-4ea7-8df6-ec138fc7c5f8.png)
still same problem

**Comment by deepsidh9** [comment]
Is the 1920x1080 branch selected?

**Comment by pintosobs** [comment]
yep 
![image](https://user-images.githubusercontent.com/69796025/148425558-2f20ba2b-d81f-42c0-8f6d-5222a67a3ed4.png)

**Comment by deepsidh9** [comment]
No  I meant is that branch selected, not the resolution

**Comment by pintosobs** [comment]
my english is not so good can u explain me what is branch

**Comment by deepsidh9** [comment]
When you clone this repository the **main** branch is selected which works for the 1920x1200 resolution. You have to type `git checkout 1920x1080` to change to the **1920x1080** branch which would work for that resolution.

**Comment by pintosobs** [comment]
Where should i type this?

**Comment by pintosobs** [comment]
ups i found it thanks

**Comment by stXwinter** [comment]
> git checkout 1920x1080

Where did you type this?
