### ISSUE TITLE
Abilites

### ISSUE THREAD

**Issue by pintosobs** [deepsidh9/Live-Valorant-Overlay#6]
![image](https://user-images.githubusercontent.com/69796025/148434541-8bced4e6-3664-4535-b9b3-7f35f704eeed.png)
Now i can see who is alive or not but i cant see which abilities they have or gun

**Comment by deepsidh9** [comment]
The gun detection works only when the scoreboard is present. You press "TAB" and if the scoreboard is successfully detected by the application, it will tell only about the guns, ultimate points and shields (if any of these are present in the scoreboard). Abilities are not available through this application.

**Comment by stXwinter** [comment]
> ![image](https://user-images.githubusercontent.com/69796025/148434541-8bced4e6-3664-4535-b9b3-7f35f704eeed.png) Now i can see who is alive or not but i cant see which abilities they have or gun

Hi can you message me on Discord @ koro#1337
