### ISSUE TITLE
-

### ISSUE THREAD

**Issue by pintosobs** [deepsidh9/Live-Valorant-Overlay#7]
![image](https://user-images.githubusercontent.com/69796025/148557788-e747c729-536f-4943-a57d-3ff80c437c1a.png)
I have this problem

**Comment by pintosobs** [comment]
It is not seeing the weapons and ult orbs

**Comment by pintosobs** [comment]
when i press tab it's giving crash

**Comment by pintosobs** [comment]
heeey can you help me??

**Comment by ArthurTelles** [comment]
@therealpintoss Any news about this issue? I'm having the same problem.

**Comment by pintosobs** [comment]
no, same

**Comment by deepsidh9** [comment]
@therealpintoss Does this happen only when you press Tab?
